### ISSUE TITLE
Command Pallete Button

### ISSUE THREAD

**Issue by Pakato** [JerryGoyal/Shortcut-Menu-Bar-VSCode-Extension#1]
Please add a Command Palette Button

**Comment by momiccioli** [comment]
I went to the command palette and clicked on "menubar: Reload" and I received an error stating that it was not found.  I would also love to add a button that another extension added to the command palette.  How do you do that too?

**Comment by JerryGoyal** [comment]
sorry for late reply. there's no "menubar: Reload" command supported from my side. not sure how you are able to see that. 
It's a nice feature to add user custom shortcuts to menubar, spare me some time and i'll look into this.

**Comment by JerryGoyal** [comment]
Hi, If you still need support let me know, meanwhile I am closing the issue.

**Comment by momiccioli** [comment]
Yes I still can’t seem to get this to work.  Can you send me instructions or a sample as to how to connect a button to a pallet command.

 

Thank you

**Comment by JerryGoyal** [comment]
I would also love to add a button 
--> Unfortunately, users can not add new buttons.  Users can only disable/enable buttons currently supported by this extension. If you need a new button you can tell me and I'll add it.

**Comment by momiccioli** [comment]
That would be great, except I would need different buttons for different workspaces.  So I don’t think it fair to ask for things that might only apply to me.  However it would be an excellent feature to have.  The two functionalities that seem to be a challenge are

 
The ability to create a button for any pallet command.  
The ability to create a button that will run a shell script. ( this exists but nice to have in a single package.)
 

And of course clear instructions on how to create the buttons.  There is lots of great contributions but doc on how to use or implement seems a bit sparse.

 

If what I am asking is not possible or out of scope then I understand and thank you.  If you are considering developing these features I would be more than happy to help test.

 

Thanks again.

**Comment by JerryGoyal** [comment]
The ability to create a button for any pallet command. 
The ability to create a button that will run a shell script.
--> I tried implementing it but didn't find any way at all. If any other extension does it then do let me know.

 So I don’t think it fair to ask for things that might only apply to me.
--> What you can do is fork this repo and make custom build according to your needs. It's fairly easy to add new buttons. see the PR https://github.com/JerryGoyal/Shortcut-Menu-Bar-VSCode-Extension/pull/5
