### ISSUE TITLE
Opened files

### ISSUE THREAD

**Issue by Poohyhu** [JerryGoyal/Shortcut-Menu-Bar-VSCode-Extension#20]
Since the new update of the VS Code, the Opened Files list isn't working as it should be.
The list doesn't popup, but switch between the opened files.

Pls look after it. thanks.

**Comment by JerryGoyal** [comment]
thanks for reporting issue. will fix it in next few days.

**Comment by JerryGoyal** [comment]
fixed.. please update the extension.
