### ISSUE TITLE
Editable buttons

### ISSUE THREAD

**Issue by DRSDavidSoft** [JerryGoyal/Shortcut-Menu-Bar-VSCode-Extension#4]
Can you add editable buttons using the `settings.json` file?

I would appreciate having **Open** and **Find** buttons in the toolbar.

**Comment by JerryGoyal** [comment]
Editable buttons are now possible. basically I will add buttons and then user can choose which buttons to show. So do you still need those buttons?

**Comment by DRSDavidSoft** [comment]
@JerryGoyal Yes, I'd appreciate editable toolbar button anytime!

Can you also make them re-order-able?

**Comment by JerryGoyal** [comment]
toolbar button 
--> sure, but what should this button do?
It is not currently possible to make re-orderable but I'll see if there's some way.

**Comment by DRSDavidSoft** [comment]
@JerryGoyal As "toolbar" I meant the "Shortcut menu".

Thanks for making the changes! :)

**Comment by JerryGoyal** [comment]
Sorry but I still doesn't get it. What should "shortcut menu" do?

**Comment by DRSDavidSoft** [comment]
I'm sorry, I basically I mean a button to open the settings page for editable buttons.

P.S. the update is wonderful! I can now enable/disable buttons like Save and Terminal :D

Thanks for the update!

**Comment by JerryGoyal** [comment]
A button to open the settings page for editable buttons
--> this is one time task so I dont think a dedicated button would be required. you can go to setting and enable/disable buttons.

Thanks.
