### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by ShalokShalom** [JerryGoyal/Shortcut-Menu-Bar-VSCode-Extension#7]
When I like my Search and Replace feature on the button, there is currently no button for it: 

![Screenshot_20190622_093919](https://user-images.githubusercontent.com/6344099/59961060-15206b80-94d2-11e9-8f07-c582305af249.png)

Once I close it, I have no option to open it again.

**Comment by JerryGoyal** [comment]
added. Please enable it from extension settings.

**Comment by ShalokShalom** [comment]
Thanks a lot. I updated to 1.39.2 and still do not see an option to toogle it with a button. 

![Screenshot_20191106_091057](https://user-images.githubusercontent.com/6344099/68280258-75750b80-0075-11ea-8452-4fed81b86920.png)

**Comment by JerryGoyal** [comment]
it's there, select shortcut menubar extension in settings page
![image](https://user-images.githubusercontent.com/7106086/68297758-bb55c200-00bd-11ea-8210-735ac6b12095.png)

**Comment by ShalokShalom** [comment]
Also in the Linux version?

![Screenshot_20191106_212123](https://user-images.githubusercontent.com/6344099/68334683-6f197a80-00db-11ea-9bcb-f3c9fc406fb8.png)

**Comment by JerryGoyal** [comment]
yes, it will work consistently on all platform where vscode can be
installed, though you need to install this extension first
