### ISSUE TITLE
External program execution

### ISSUE THREAD

**Issue by e14mattc** [JerryGoyal/Shortcut-Menu-Bar-VSCode-Extension#8]
I'd like a bunch of optional buttons that allow you to execute external scripts, and have the ability to pass what filename is currently in focus, what line of code the cursor is on, etc. 

Pretty much like Notepad++ does here;
http://docs.notepad-plus-plus.org/index.php/External_Programs

Being able to set a custom icon + tooltip would be essential.

**Comment by slavdok** [comment]
+1

**Comment by JerryGoyal** [comment]
Sorry, not technically feasible, it's a limitation in VSCode, you can't modify package.json of extension where the buttons are configured.
