### ISSUE TITLE
Where did the Save menu button go?

### ISSUE THREAD

**Issue by alekdavis** [JerryGoyal/Shortcut-Menu-Bar-VSCode-Extension#9]
I know it was there before, but now it disappeared:

![ShortcutMenuBar](https://user-images.githubusercontent.com/2113681/63041343-7cc4b880-be7c-11e9-801b-066b29e3e3e5.PNG)

Was it removed from the extension?

**Comment by JerryGoyal** [comment]
hi, it must've been disabled by default. u can enable it in shortcut menu bar extension preferences.
![image](https://user-images.githubusercontent.com/7106086/63226832-e395f900-c211-11e9-9760-802a56908ae1.png)

**Comment by alekdavis** [comment]
Yep, that was it. Thank you.
